@startuml

actor Пользователь

participant DeviceService
participant UserService
participant Kafka
participant TelemetryService

Пользователь -> DeviceService: Запрос на добавление модуля в дом
DeviceService -> Пользователь: Подтверждение запроса (Верификаиция модуля начата)
DeviceService -> Kafka: Публикует событие "module.added"

Kafka -> UserService: Потребляет событие "module.added"
UserService -> UserService: Проверяет дом и права доступа
alt Дом существует и у пользователя есть права
    UserService -> Kafka: Публикует событие "module.verification.succeeded"
else Дом не существует или у пользователя нет прав
    UserService -> Kafka: Публикует событие "module.verification.failed"
end

Kafka -> DeviceService: Потребляет событие "module.verification.succeeded" или "module.verification.failed"
alt Верификация успешна
    DeviceService -> DeviceService: Обновляет статус на PENDING_INSTALL
    DeviceService -> Kafka: Публикует событие "module.installed"
else Верификация провалилась
    DeviceService -> DeviceService: Обновляет статус на PENDING_FAILED
end

Kafka -> TelemetryService: Потребляет событие "module.installed"
TelemetryService -> TelemetryService: Логирует успешную установку модуля

@enduml
