@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(customer, "Клиент", "Пользователь системы отопления")

System_Boundary(monolith, "Система контроля отоплением") {
    Container(server, "Сервер", "Java Spring Backend", "Управляет логикой управления отоплением и взаимодействует с датчиками температуры в помещении")
    Container(mobile_app, "Мобильное приложение", "iOS/Android", "Позволяет клиенту управлять отоплением и просматривать данные о температуре")
}

System_Ext(system, "Отопительное оборудование", "Heating Equipment")
System_Ext(sensor, "Температурный датчик", "Temperature Sensor")

Rel(customer, mobile_app, "Использует для управления отоплением через мобильное приложение")
Rel(mobile_app, server, "Отправляет HTTP-запросы для управления отоплением и получения данных о температуре")
Rel(server, system, "Отправляет команды для управления отоплением")
Rel_L(sensor, server, "Получает данные о температуре в помещении")

@enduml
