@startuml
!include <C4/C4_Container>

LAYOUT_WITH_LEGEND()

System_Ext(internal_system, "Внутренняя Система", "Запускает процессы и взаимодействует с DeviceService для управления модулями")
System_Ext(external_system, "Внешняя Система", "Генерирует события и отправляет их в Kafka")

System_Boundary(b_system, "Device Service") {
    Container(device_service, "DeviceService", "Golang", "Управляет модулями: подключение, получение списка, включение/выключение")
    ContainerDb(modules_db, "База Данных Модулей", "PostgreSQL", "Хранит информацию о подключенных модулях и их состоянии")
    ContainerQueue(kafka_broker, "Kafka", "Брокер Сообщений", "Обрабатывает события системы")
}

Rel(internal_system, device_service, "Вызывает сервис для управления модулями", "HTTP/HTTPS")
Rel(device_service, modules_db, "Читает и записывает данные о модулях", "PostgreSQL драйвер")
Rel(device_service, kafka_broker, "Публикует события о состоянии модулей", "module.events.topic")
Rel(external_system, kafka_broker, "Отправляет события на обработку", "event.input.topic")

@enduml
