@startuml
!include <C4/C4_Container>

skinparam linetype ortho
skinparam rectangle {
  BackgroundColor #white
  BorderColor #black
  Shadowing false
}

Person(client, "Клиент", "Пользователь, взаимодействующий с UserService через API")

System_Boundary(b_system, "User Service") {
    Container(user_service, "UserService", "Golang", "Управляет информацией о пользователях и верификацией домов")

    ContainerDb(user_db, "База Данных Пользователей", "PostgreSQL", "Хранит данные о пользователях")

    Container(kafka_broker, "Kafka", "Брокер Сообщений", "Обрабатывает события системы")
}

Rel(client, user_service, "Запросы к API (включая JWT аутентификацию)", "HTTP/HTTPS + JWT")
Rel(user_service, user_db, "Читает и записывает данные пользователей", "PostgreSQL драйвер")
Rel(kafka_broker, user_service, "Получает ивент на верификацию", "verification.result")
Rel(user_service, kafka_broker, "Отправляет ответный ивент с результатом верификации", "client.verification")

@enduml
